### ISSUE TITLE
Creating challenges interface

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/mesure.x10.mx#56] opened 2024-01-30 14:38 UTC
### Issue Contents

Creating the logic that loads the challenges onto the page and executes them.
Note that for now, **challenge javascript code can be run in `script.js` because only @Mesure73L is writing them, but when custom challenges packs come out, it must move to another file.**

**Comment by Mesure73L** [comment] 2024-01-30 14:39
Is this a duplicate of #47?

**Comment by BeepBot99** [comment] 2024-01-30 14:40
No, because that is for running it in a different file, which as explained, will be done in 1.1.0. This is for just making it work even if it runs in the same file, which will be done in 1.0.0.

**Comment by Mesure73L** [comment] 2024-01-30 14:42
Making what work?

**Comment by Mesure73L** [comment] 2024-01-30 14:46
> This is for just making it work even if it runs in the same file, which will be done in 1.0.0.
@BeepBot99 the JavaScript code already runs in the `script.js`, is that what this issue is for?

**Comment by BeepBot99** [comment] 2024-01-30 14:52
Kind of. This issue is for completely making the challenges work.

**Comment by Mesure73L** [comment] 2024-01-30 14:53
Then this is done. I created functionality in the `12oc-making-challenges` branch (if it's deleted because you merge main into it then that's your fault).

**Comment by BeepBot99** [comment] 2024-01-30 14:57
No, it is not completed until it is merged.
Create a pull request and say "Closes #56"
PS: Why would I merge main into it? In addition, even if I did for some reason, it is still saved in the commit history.

**Comment by Mesure73L** [comment] 2024-01-30 14:58
Don't you remember? You updated the branch last night.

**Comment by BeepBot99** [comment] 2024-01-30 15:00
No, I merged main into creating-settings.

**Comment by BeepBot99** [comment] 2024-01-30 15:05
@Mesure73L Please do not edit the project. I am doing that.

**Comment by Mesure73L** [comment] 2024-01-30 15:47
> @Mesure73L Please do not edit the project. I am doing that.

We should still have the paused category

**Closed** 2024-01-31 00:42 UTC
Labels: twelve of code
