### ISSUE TITLE
Add checkboxes in issues

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/mesure.x10.mx#55] opened 2024-01-30 05:03 UTC
### Issue Contents

Like this:
```markdown
- [ ] task one
- [x] task two is completed
```
That way, you can see the percentage completed for each issue, and it will contribute to the percentage completed for the milestone.

**Comment by Mesure73L** [comment] 2024-01-30 05:04
Kind of a duplicate of #54, closing this as a duplicate (we can put this there as its kind of related)

**Closed by Mesure73L** 2024-01-30 05:04 UTC
